### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by sleekka** [aw/picolisp-https#7]
When I do tests by: make check
I had a mistake: make: *** [run-tests] Segmentation fault
I think this is may be recursion error, but I can't to fix it

**Comment by aw** [comment]
Hello,

I just pushed a "new" build to Travis-ci and it still seems to build fine:

https://travis-ci.org/aw/picolisp-https/builds/198309958

**Comment by sleekka** [comment]
I installed picolisp from repositories, and now i rebuild it from source 64, but I have the same error.
Here is log:
```
~/progs/aw/picolisp-https# make check
mkdir -p .lib && \
		cd .lib && \
		ln -sf ../.modules/neon/HEAD/src/.libs/libneon.so libneon.so
mkdir -p .modules/picolisp-unit/HEAD && \
		git clone https://github.com/aw/picolisp-unit.git .modules/picolisp-unit/HEAD
Cloning into '.modules/picolisp-unit/HEAD'...
remote: Counting objects: 169, done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 169 (delta 0), reused 0 (delta 0), pack-reused 166
Receiving objects: 100% (169/169), 37.95 KiB | 0 bytes/s, done.
Resolving deltas: 100% (86/86), done.
Checking connectivity... done.
./test.l

  Testing HTTP(S) client for PicoLisp

make: *** [run-tests] Segmentation fault
~/progs/aw/picolisp-https# pil -ver
!? (ver)
ver -- Undefined
? ~/progs/aw/picolisp-https# pil +
: (ver)
!? (ver)
ver -- Undefined
?      
~/progs/aw/picolisp-https# pil -version
3.1.5.2
: ~/progs/aw/picolisp-https# apt-get remove picolisp
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages will be REMOVED:
  picolisp
0 upgraded, 0 newly installed, 1 to remove and 357 not upgraded.
After this operation, 4,355 kB disk space will be freed.
Do you want to continue? [Y/n] Y
(Reading database ... 169299 files and directories currently installed.)
Removing picolisp (3.1.5.2-2) ...
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
~/progs/aw/picolisp-https# cd
~# wget http://software-lab.de/picoLisp-16.12.tgz -O /tmp/picolisp.tgz
--2017-02-04 11:25:13--  http://software-lab.de/picoLisp-16.12.tgz
Resolving software-lab.de (software-lab.de)... 81.169.145.86, 2a01:238:20a:202:1086::
Connecting to software-lab.de (software-lab.de)|81.169.145.86|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 983744 (961K) [text/plain]
Saving to: ‘/tmp/picolisp.tgz’

100%[==========================================================================================>] 983,744      277KB/s   in 3.5s   

2017-02-04 11:25:17 (277 KB/s) - ‘/tmp/picolisp.tgz’ saved [983744/983744]

~# cd /tmp; tar -xf /tmp/picolisp.tgz
/tmp# cd /tmp/picoLisp/src64 && make
./mkAsm x86-64 ".linux" .s Linux base "" ../lib/map  version.l glob.l main.l gc.l apply.l flow.l sym.l subr.l big.l io.l db.l net.l err.l sys/x86-64.linux.code.l
as -o x86-64.linux.base.o x86-64.linux.base.s
cc -o ../bin/picolisp x86-64.linux.base.o -Wl,--no-as-needed -rdynamic -lc -lm -ldl 
strip ../bin/picolisp
./mkAsm x86-64 ".linux" .s Linux ext T ""  ext.l
as -o x86-64.linux.ext.o x86-64.linux.ext.s
cc -o ../lib/ext x86-64.linux.ext.o -shared -export-dynamic
strip ../lib/ext
./mkAsm x86-64 ".linux" .s Linux ht T ""  ht.l
as -o x86-64.linux.ht.o x86-64.linux.ht.s
cc -o ../lib/ht x86-64.linux.ht.o -shared -export-dynamic
strip ../lib/ht
/tmp/picoLisp/src64# export PATH=$PATH:/tmp/picoLisp
/tmp/picoLisp/src64# 
/tmp/picoLisp/src64# cd
~# cd progs/aw/picolisp-https/
~/progs/aw/picolisp-https# make check
mkdir -p .lib && \
		cd .lib && \
		ln -sf ../.modules/neon/HEAD/src/.libs/libneon.so libneon.so
./test.l

  Testing HTTP(S) client for PicoLisp

make: *** [run-tests] Segmentation fault
~/progs/aw/picolisp-https# cd
~# cd /var/log/syslog
bash: cd: /var/log/syslog: Not a directory
~# cd var/log/syslog
bash: cd: var/log/syslog: No such file or directory
~# pwd
/home/sl
~# cd /var/log/syslog
bash: cd: /var/log/syslog: Not a directory
~# ^C
~# pil -version
16.12.8
: ~# ^C
~# 

```

**Comment by aw** [comment]
Oh that's weird.. Does your system already have its own version of `libneon` ? You can check with this: `dpkg -l | grep libneon`

Also I'd like to see where it segfaults:

```
pil +
(traceAll)
(load "https.l")
```

Thanks!

**Comment by sleekka** [comment]
Thank you for helping me.
I'm noob in linux.
here is log after traceAll:

> Testing HTTP(S) client for PicoLisp
> 
>  chdir : "test/" ((mapcar load (filter '((N) (sub? "test_" N)) (dir "."))))
> Segmentation fault

**Comment by aw** [comment]
@sleekka sorry, I can't debug that. Please paste output from what I wrote in my previous comment.

**Comment by sleekka** [comment]
Ok. Please.

> a@a-virtual-machine:~$ sudo -s

> [sudo] password for a: 
> root@a-virtual-machine:~# cd /usr/share/picolisp
> root@a-virtual-machine:/usr/share/picolisp# cd picolisp-https/
> root@a-virtual-machine:/usr/share/picolisp/picolisp-https# dpkg -l | grep libneon
> ii  libneon27-gnutls                                            0.30.0-1ubuntu1                                             amd64        HTTP and WebDAV client library (GnuTLS enabled)
> root@a-virtual-machine:/usr/share/picolisp/picolisp-https# pil +
> : (traceAll)
> -> T
> : (load "https.l")
>  local : (MODULE_INFO *Https *Buffer_size *Headers)
>  local = "*Headers"
>  local : (*NE_FEATURE_SSL *NE_FEATURE_ZLIB *NE_FEATURE_IPV6 *NE_FEATURE_LFS *NE_FEATURE_SOCKS)
>  local = "*NE_FEATURE_SOCKS"
>  local : (*NE_FEATURE_TS_SSL *NE_FEATURE_I18N *NE_FEATURE_SSPI)
>  local = "*NE_FEATURE_SSPI"
>  local : (*NE_ABUFSIZ *NE_OK *NE_ERROR *NE_LOOKUP *NE_AUTH *NE_PROXYAUTH *NE_CONNECT)
>  local = "*NE_CONNECT"
>  local : (*NE_TIMEOUT *NE_FAILED *NE_RETRY *NE_REDIRECT)
>  local = "*NE_REDIRECT"
>  local : (ne-sock-init ne-version-string ne-has-support ne-get-error ne-uri-parse ne-uri-defaultport)
>  local = "ne-uri-defaultport"
>  local : (ne-add-request-header ne-session-create ne-ssl-trust-default-ca ne-request-create)
>  local = "ne-request-create"
>  local : (ne-begin-request ne-end-request ne-read-response-block ne-read-response-to-fd ne-set-request-body-buffer)
>  local = "ne-set-request-body-buffer"
>  local : (ne-request-destroy ne-close-connection ne-session-destroy ne-get-status ne-response-header-iterate)
>  local = "ne-response-header-iterate"
>  local : (ne-set-server-auth ne-forget-auth)
>  local = "ne-forget-auth"
>  local : (throw-error create-session-request create-session parse-uri get-port set-auth-credentials)
>  local = "set-auth-credentials"
>  local : (do-auth del-auth-credentials set-headers set-request-body request-dispatch download-file random-filename random-id)
>  local = "random-id"
>  local : (process-body link-response-block pack-body parse-response get-headers end-request-session end-session)
>  local = "end-session"
>  local : (begin-request end-request)
>  local = "end-request"
> -> "req"
> : (load "test.l") 
>  local : (MODULE_INFO *My_tests_are_order_dependent *Results)
>  local = "*Results"
>  local : (randomize passed failed queue-results colour plural? get-results)
>  local = "get-results"
>  local : (*Colours print-report print-passed print-failed report-failed print-error)
>  local = "print-error"
>  local : (print-expected print-got exit-gracefully)
>  local = "exit-gracefully"
> # https redefined
>  local : (MODULE_INFO *Https *Buffer_size *Headers)
>  local = "*Headers"
>  local : (*NE_FEATURE_SSL *NE_FEATURE_ZLIB *NE_FEATURE_IPV6 *NE_FEATURE_LFS *NE_FEATURE_SOCKS)
>  local = "*NE_FEATURE_SOCKS"
>  local : (*NE_FEATURE_TS_SSL *NE_FEATURE_I18N *NE_FEATURE_SSPI)
>  local = "*NE_FEATURE_SSPI"
>  local : (*NE_ABUFSIZ *NE_OK *NE_ERROR *NE_LOOKUP *NE_AUTH *NE_PROXYAUTH *NE_CONNECT)
>  local = "*NE_CONNECT"
>  local : (*NE_TIMEOUT *NE_FAILED *NE_RETRY *NE_REDIRECT)
>  local = "*NE_REDIRECT"
>  local : (ne-sock-init ne-version-string ne-has-support ne-get-error ne-uri-parse ne-uri-defaultport)
>  local = "ne-uri-defaultport"
>  local : (ne-add-request-header ne-session-create ne-ssl-trust-default-ca ne-request-create)
>  local = "ne-request-create"
>  local : (ne-begin-request ne-end-request ne-read-response-block ne-read-response-to-fd ne-set-request-body-buffer)
>  local = "ne-set-request-body-buffer"
>  local : (ne-request-destroy ne-close-connection ne-session-destroy ne-get-status ne-response-header-iterate)
>  local = "ne-response-header-iterate"
>  local : (ne-set-server-auth ne-forget-auth)
>  local = "ne-forget-auth"
>  local : (throw-error create-session-request create-session parse-uri get-port set-auth-credentials)
>  local = "set-auth-credentials"
>  local : (do-auth del-auth-credentials set-headers set-request-body request-dispatch download-file random-filename random-id)
>  local = "random-id"
>  local : (process-body link-response-block pack-body parse-response get-headers end-request-session end-session)
>  local = "end-session"
>  local : (begin-request end-request)
>  local = "end-request"
> 
>   Testing HTTP(S) client for PicoLisp
> 
>  chdir : "test/" ((mapcar load (filter '((N) (sub? "test_" N)) (dir "."))))
> Segmentation fault
> root@a-virtual-machine:/usr/share/picolisp/picolisp-https# 
>

**Comment by sleekka** [comment]
aw, sorry I forgot to make new version of Pil
this is log with newest version:

> root@a-virtual-machine:~# wget http://software-lab.de/picoLisp-16.12.tgz -O /usr/share/picolisp.tgz
> --2017-02-08 14:39:46--  http://software-lab.de/picoLisp-16.12.tgz
> Resolving software-lab.de (software-lab.de)... 81.169.145.86, 2a01:238:20a:202:1086::
> Connecting to software-lab.de (software-lab.de)|81.169.145.86|:80... connected.
> HTTP request sent, awaiting response... 200 OK
> Length: 983744 (961K) [text/plain]
> Saving to: ‘/usr/share/picolisp.tgz’
> 
> 100%[======================================>] 983 744      221KB/s   in 4,5s   
> 
> 2017-02-08 14:39:51 (212 KB/s) - ‘/usr/share/picolisp.tgz’ saved [983744/983744]
> 
> root@a-virtual-machine:~# cd /usr/share
> root@a-virtual-machine:/usr/share# cd /usr/share; tar -xf /usr/share/picolisp.tgz
> root@a-virtual-machine:/usr/share# cd /usr/share/picoLisp/src64 && make
> ./mkAsm x86-64 ".linux" .s Linux base "" ../lib/map  version.l glob.l main.l gc.l apply.l flow.l sym.l subr.l big.l io.l db.l net.l err.l sys/x86-64.linux.code.l
> as -o x86-64.linux.base.o x86-64.linux.base.s
> cc -o ../bin/picolisp x86-64.linux.base.o -Wl,--no-as-needed -rdynamic -lc -lm -ldl 
> strip ../bin/picolisp
> ./mkAsm x86-64 ".linux" .s Linux ext T ""  ext.l
> as -o x86-64.linux.ext.o x86-64.linux.ext.s
> cc -o ../lib/ext x86-64.linux.ext.o -shared -export-dynamic
> strip ../lib/ext
> ./mkAsm x86-64 ".linux" .s Linux ht T ""  ht.l
> as -o x86-64.linux.ht.o x86-64.linux.ht.s
> cc -o ../lib/ht x86-64.linux.ht.o -shared -export-dynamic
> strip ../lib/ht
> root@a-virtual-machine:/usr/share/picoLisp/src64# export PATH=$PATH:/usr/share/picoLisp
> root@a-virtual-machine:/usr/share/picoLisp/src64# cd ..
> root@a-virtual-machine:/usr/share/picoLisp# cd picolisp-https/
> root@a-virtual-machine:/usr/share/picoLisp/picolisp-https# pil+
> bash: pil+: command not found
> root@a-virtual-machine:/usr/share/picoLisp/picolisp-https# pil +
> : (traceAll)
> -> T
> : (load "https.l")
>  local : (MODULE_INFO *Https *Buffer_size *Headers)
>  local = "*Headers"
>  local : (*NE_FEATURE_SSL *NE_FEATURE_ZLIB *NE_FEATURE_IPV6 *NE_FEATURE_LFS *NE_FEATURE_SOCKS)
>  local = "*NE_FEATURE_SOCKS"
>  local : (*NE_FEATURE_TS_SSL *NE_FEATURE_I18N *NE_FEATURE_SSPI)
>  local = "*NE_FEATURE_SSPI"
>  local : (*NE_ABUFSIZ *NE_OK *NE_ERROR *NE_LOOKUP *NE_AUTH *NE_PROXYAUTH *NE_CONNECT)
>  local = "*NE_CONNECT"
>  local : (*NE_TIMEOUT *NE_FAILED *NE_RETRY *NE_REDIRECT)
>  local = "*NE_REDIRECT"
>  local : (ne-sock-init ne-version-string ne-has-support ne-get-error ne-uri-parse ne-uri-defaultport)
>  local = "ne-uri-defaultport"
>  local : (ne-add-request-header ne-session-create ne-ssl-trust-default-ca ne-request-create)
>  local = "ne-request-create"
>  local : (ne-begin-request ne-end-request ne-read-response-block ne-read-response-to-fd ne-set-request-body-buffer)
>  local = "ne-set-request-body-buffer"
>  local : (ne-request-destroy ne-close-connection ne-session-destroy ne-get-status ne-response-header-iterate)
>  local = "ne-response-header-iterate"
>  local : (ne-set-server-auth ne-forget-auth)
>  local = "ne-forget-auth"
>  local : (throw-error create-session-request create-session parse-uri get-port set-auth-credentials)
>  local = "set-auth-credentials"
>  local : (do-auth del-auth-credentials set-headers set-request-body request-dispatch download-file random-filename random-id)
>  local = "random-id"
>  local : (process-body link-response-block pack-body parse-response get-headers end-request-session end-session)
>  local = "end-session"
>  local : (begin-request end-request)
>  local = "end-request"
> -> "req"
> : (load "test.l")
>  local : (MODULE_INFO *My_tests_are_order_dependent *Results)
>  local = "*Results"
>  local : (randomize passed failed queue-results colour plural? get-results)
>  local = "get-results"
>  local : (*Colours print-report print-passed print-failed report-failed print-error)
>  local = "print-error"
>  local : (print-expected print-got exit-gracefully)
>  local = "exit-gracefully"
> # https redefined
>  local : (MODULE_INFO *Https *Buffer_size *Headers)
>  local = "*Headers"
>  local : (*NE_FEATURE_SSL *NE_FEATURE_ZLIB *NE_FEATURE_IPV6 *NE_FEATURE_LFS *NE_FEATURE_SOCKS)
>  local = "*NE_FEATURE_SOCKS"
>  local : (*NE_FEATURE_TS_SSL *NE_FEATURE_I18N *NE_FEATURE_SSPI)
>  local = "*NE_FEATURE_SSPI"
>  local : (*NE_ABUFSIZ *NE_OK *NE_ERROR *NE_LOOKUP *NE_AUTH *NE_PROXYAUTH *NE_CONNECT)
>  local = "*NE_CONNECT"
>  local : (*NE_TIMEOUT *NE_FAILED *NE_RETRY *NE_REDIRECT)
>  local = "*NE_REDIRECT"
>  local : (ne-sock-init ne-version-string ne-has-support ne-get-error ne-uri-parse ne-uri-defaultport)
>  local = "ne-uri-defaultport"
>  local : (ne-add-request-header ne-session-create ne-ssl-trust-default-ca ne-request-create)
>  local = "ne-request-create"
>  local : (ne-begin-request ne-end-request ne-read-response-block ne-read-response-to-fd ne-set-request-body-buffer)
>  local = "ne-set-request-body-buffer"
>  local : (ne-request-destroy ne-close-connection ne-session-destroy ne-get-status ne-response-header-iterate)
>  local = "ne-response-header-iterate"
>  local : (ne-set-server-auth ne-forget-auth)
>  local = "ne-forget-auth"
>  local : (throw-error create-session-request create-session parse-uri get-port set-auth-credentials)
>  local = "set-auth-credentials"
>  local : (do-auth del-auth-credentials set-headers set-request-body request-dispatch download-file random-filename random-id)
>  local = "random-id"
>  local : (process-body link-response-block pack-body parse-response get-headers end-request-session end-session)
>  local = "end-session"
>  local : (begin-request end-request)
>  local = "end-request"
> 
>   Testing HTTP(S) client for PicoLisp
> 
>  chdir : "test/" ((mapcar load (filter '((N) (sub? "test_" N)) (dir "."))))
>   hex : 1393565627 NIL
>    hex1 : 1393565627
>    hex1 = "B"
>    hex1 : 87097851
>    hex1 = "B"
>    hex1 : 5443615
>    hex1 = "F"
>    hex1 : 340225
>    hex1 = "1"
>    hex1 : 21264
>    hex1 = "0"
>    hex1 : 1329
>    hex1 = "1"
>    hex1 : 83
>    hex1 = "3"
>    hex1 : 5
>    hex1 = "5"
>   hex = "53101FBB"
>   tmp : "dl-" "53101fbb" "-" 1 ".tmp"
>    pil : "tmp/" 5768 "/"
>    pil = "/home/a/.pil/tmp/5768/"
>   tmp = "/home/a/.pil/tmp/5768/dl-53101fbb-1.tmp"
> Segmentation fault
> root@a-virtual-machine:/usr/share/picoLisp/picolisp-https# pil -version
> 16.12.8

**Comment by aw** [comment]
@sleekka Thanks for the output log.

I'll look into it later this week.

**Comment by sleekka** [comment]
aw, have you got a good news?

**Comment by aw** [comment]
Sorry, it works on every system I tested, so I don't know..

Maybe you should try on a system that doesn't include its own version of `libneon`.

**Comment by sleekka** [comment]
I tested it in ubuntu based 14 04 in 2 systems
I had force remove libneon.
I install first picolisp and than https-lib.
I have the same result again and agian. Have you got any ideas?
  

> Testing HTTP(S) client for PicoLisp
> 
>  chdir : "test/" ((mapcar load (filter '((N) (sub? "test_" N)) (dir "."))))
>   hex : 1566331223 NIL
>    hex1 : 1566331223
>    hex1 = "7"
>    hex1 : 97895701
>    hex1 = "5"
>    hex1 : 6118481
>    hex1 = "1"
>    hex1 : 382405
>    hex1 = "5"
>    hex1 : 23900
>    hex1 = "C"
>    hex1 : 1493
>    hex1 = "5"
>    hex1 : 93
>    hex1 = "D"
>    hex1 : 5
>    hex1 = "5"
>   hex = "5D5C5157"
>   tmp : "dl-" "5d5c5157" "-" 1 ".tmp"
>    pil : "tmp/" 5901 "/"
>    pil = "/home/sl/.pil/tmp/5901/"
>   tmp = "/home/sl/.pil/tmp/5901/dl-5d5c5157-1.tmp"
> Segmentation fault


What means "Segmentation fault" ?

**Comment by sleekka** [comment]
If i go to .modules/neon/HEAD
and do make install
I have an error

> root@sl-dell:~/picolisp-https/.modules/neon/HEAD# make install
> make[1]: Entering directory `/home/sl/picolisp-https/.modules/neon/HEAD/src'
> make[1]: Nothing to be done for `all'.
> make[1]: Leaving directory `/home/sl/picolisp-https/.modules/neon/HEAD/src'
> /usr/bin/install -c -d /usr/local/lib
> /bin/bash ./libtool --mode=install /usr/bin/install -c src/libneon.la \
> 		/usr/local/lib/libneon.la
> libtool: install: /usr/bin/install -c src/.libs/libneon.so.27.3.1 /usr/local/lib/libneon.so.27.3.1
> libtool: install: (cd /usr/local/lib && { ln -s -f libneon.so.27.3.1 libneon.so.27 || { rm -f libneon.so.27 && ln -s libneon.so.27.3.1 libneon.so.27; }; })
> libtool: install: (cd /usr/local/lib && { ln -s -f libneon.so.27.3.1 libneon.so || { rm -f libneon.so && ln -s libneon.so.27.3.1 libneon.so; }; })
> libtool: install: /usr/bin/install -c src/.libs/libneon.lai /usr/local/lib/libneon.la
> libtool: install: /usr/bin/install -c src/.libs/libneon.a /usr/local/lib/libneon.a
> libtool: install: chmod 644 /usr/local/lib/libneon.a
> libtool: install: /usr/bin/ranlib /usr/local/lib/libneon.a
> libtool: finish: PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/progs/picoLisp:/sbin" ldconfig -n /usr/local/lib
> ----------------------------------------------------------------------
> Libraries have been installed in:
>    /usr/local/lib
> 
> If you ever happen to want to link against installed libraries
> in a given directory, LIBDIR, you must either use libtool, and
> specify the full pathname of the library, or use the `-LLIBDIR'
> flag during linking and do at least one of the following:
>    - add LIBDIR to the `LD_LIBRARY_PATH' environment variable
>      during execution
>    - add LIBDIR to the `LD_RUN_PATH' environment variable
>      during linking
>    - use the `-Wl,-rpath -Wl,LIBDIR' linker flag
>    - have your system administrator add LIBDIR to `/etc/ld.so.conf'
> 
> See any operating system documentation about shared libraries for
> more information, such as the ld(1) and ld.so(8) manual pages.
> ----------------------------------------------------------------------
> /usr/bin/install -c -d /usr/local/include/neon
> Installing ne_request.h into /usr/local/include/neon
> Installing ne_session.h into /usr/local/include/neon
> Installing ne_utils.h into /usr/local/include/neon
> Installing ne_uri.h into /usr/local/include/neon
> Installing ne_socket.h into /usr/local/include/neon
> Installing ne_basic.h into /usr/local/include/neon
> Installing ne_207.h into /usr/local/include/neon
> Installing ne_props.h into /usr/local/include/neon
> Installing ne_xml.h into /usr/local/include/neon
> Installing ne_dates.h into /usr/local/include/neon
> Installing ne_string.h into /usr/local/include/neon
> Installing ne_defs.h into /usr/local/include/neon
> Installing ne_locks.h into /usr/local/include/neon
> Installing ne_alloc.h into /usr/local/include/neon
> Installing ne_md5.h into /usr/local/include/neon
> Installing ne_i18n.h into /usr/local/include/neon
> Installing ne_redirect.h into /usr/local/include/neon
> Installing ne_auth.h into /usr/local/include/neon
> Installing ne_compress.h into /usr/local/include/neon
> Installing ne_acl.h into /usr/local/include/neon
> Installing ne_ssl.h into /usr/local/include/neon
> Installing ne_xmlreq.h into /usr/local/include/neon
> Installing ne_pkcs11.h into /usr/local/include/neon
> Installing ne_acl3744.h into /usr/local/include/neon
> /usr/bin/install -c -d /usr/local/bin
> Installing neon-config into /usr/local/bin
> /usr/bin/install -c -d /usr/local/lib/pkgconfig
> /usr/bin/install -c -m 644 neon.pc /usr/local/lib/pkgconfig/neon.pc
> /usr/bin/install -c -d /usr/local/share/man/man3
> /usr/bin/install -c -d /usr/local/share/man/man1
> for m in ./doc/man/*.3; do \
> 	 /usr/bin/install -c -m 644 $m /usr/local/share/man/man3; done
> /usr/bin/install: cannot stat ‘./doc/man/*.3’: No such file or directory
> make: *** [install-man] Error 1
>

**Comment by aw** [comment]
Sorry, I can't magically fix this for you, because it's a system problem on your end.

You can check the [Travis-ci build logs here](https://s3.amazonaws.com/archive.travis-ci.org/jobs/198309959/log.txt)

It runs perfectly on Ubuntu with the configuration of the Travis build server, as well as on my own Debian and TinyCore Linux servers.

**Comment by sleekka** [comment]
Thank you so match, i hope that i will find my problem.
